### ISSUE TITLE
Internal Server Error when "Loading all services" in new repo with NAS blueprint

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#120]
Maybe not related to the blueprint?

```yaml
g8client__gig:
    g8.url: 'gig.demo.greenitglobe.com'
    g8.login: 'yves'
    g8.password: 'IAM4greenIT'
    g8.account: 'Account of Yves'

vdcfarm__farm1:

vdc__vdc4nas1:
    vdcfarm: 'farm1'
    g8.client.name: 'gig'
    g8.location: 'du-conv-1'        

node.ovc__vm1:
    os.image: 'ubuntu 16.04 x64'
    disk.size: 10
    datadisks:
        - 'name:disk1 size:50 type:normal'
        - 'name:disk2 size:50 type:normal'
    os.size: 2
    ports:
        - '139:139'
        - '445:445'
        - '137:137'
        - '138:138'
    vdc: 'vdc4nas1'

os.ssh.ubuntu__os_vm1:
    node: 'vm1'
    aysfs: false
    authorized_keys:
        - ""

user.os__yves:
    password: 'ifilebugs'
    os: os_vm1

blockdevice.raid__vm_share1:
    os: 'os_vm1'
    disks:
        - 'disk1'
        - 'disk2'
    raid: 0

mount__nas1:
    blockdevice: 'vm_share1'
    filesystem: 'ext4'
    location: '/var/nas'
    options: 'rw'
    os: 'os_vm1'
        
share.samba__share1:
    mount: 'nas1'
    users:
        - 'yves'
```
