### ISSUE TITLE
Install a BP to deploy a CS which is already deployed doesn't update its properties

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#134]
**Steps**
- Create a CS in du-conv-2 with name "checkdeleteissue". Its ID is 1647
![screenshot from 2016-07-21 13-39-43](https://cloud.githubusercontent.com/assets/17981089/17021490/fbf61df4-4f50-11e6-83dc-b3c1d51dcb21.png)

- Create a new Repo in a cockpit and enter this bp which will install a CS with "checkdeleteissue" (same CS in the same env)

```
g8client__dubai:
   g8.url: 'du-conv-2.demo.greenitglobe.com'
   g8.login: 'gig'
   g8.password: 'KrOe6gE9K5nCQdmretfXnj'
   g8.account: 'gig'
 
vdc__checkdeleteissue:
  g8.client.name: 'dubai'
   maxMemoryCapacity: 2
   maxVDiskCapacity: 10
   maxCPUCapacity: 2
   maxNASCapacity: 20
   maxArchiveCapacity: 20
   maxNetworkOptTransfer: 5
   maxNetworkPeerTransfer: 15
   maxNumPublicIP: 1
```

- Execute BP
- Init Repo
- Install 
![screenshot from 2016-07-21 13-43-44](https://cloud.githubusercontent.com/assets/17981089/17021573/8ad63c70-4f51-11e6-9358-caaa72da7506.png)

- Check the Repo instance
![screenshot from 2016-07-21 13-44-36](https://cloud.githubusercontent.com/assets/17981089/17022291/d6524b0e-4f55-11e6-9df9-16e88e7401fd.png)

**Expected result**
Cockpit should check if this CS is already deployed and if yes, It must produce an error message.
