### ISSUE TITLE
Installing vm on existing vdc via cockpit doesn't work

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#140]
I first created a vdc via Moehaha, result was successful: https://gig.demo.greenitglobe.com/CBGrid/Cloud%20Space?id=61

Then I add a first VM via the Control Panel, result was successful:
https://gig.demo.greenitglobe.com/CBGrid/Virtual%20Machine?id=1212

However when trying to add another VM to the cloud space using Cockpit, it simply didn't work - without any error...

Doing an install, even if I explicitly specify to install saturday1_vm2, not happens, not even any trace under Runs...

Here's the blueprint, also see screenshot:

``` yaml
node.ovc__saturday1_vm2:
    os.image: 'ubuntu 16.04 x64'
    disk.size: 10
    datadisks:
        - 'name:disk1 size:50 type:normal'
        - 'name:disk2 size:50 type:normal'
    os.size: 2
    ports:
        - '2322:22'
    vdc: 'saturday'

os.ssh.ubuntu__os_vm:
    node: 'saturday1_vm2'
    aysfs: false
    authorized_keys:
        - ""

user.os__yves:
    password: 'ifilebugs'
    os: os_vm
```

![screen shot 2016-07-23 at 15 16 08](https://cloud.githubusercontent.com/assets/13795109/17078047/6c9353cc-50e8-11e6-9d2e-47e2e99221a9.png)
