### ISSUE TITLE
Adding users through a blueprint doesn't work

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#159]
The below is supposed to add/create new user to a vm:
```yaml
user.os__yves:
    password: 'ifilebugs'
    os: os_vm
```
When logging in with cloudscalers and checking all users, you'll see the user was not created:
`awk -F":" '{ print "username: " $1 "\t\tuid:" $3 }' /etc/passwd`
