### ISSUE TITLE
cockpit_portal: cockpit doesn't report errors

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#183]
**Description**
Cockpit doesn't report errors which are producing when install a wrong blueprint.

> **Steps**
> - Add the following blueprint to the cockpit repo

``` yaml
g8client__cockpittest:
  g8.url: 'gig.demo.greenitglobe.com'
  g8.login: 'gig'
  g8.password: 'KrOe6gE9K5nCQdmretfXnj'
  g8.account: 'gig'

vdc__helloislam:
  g8.client.name: 'cockpittest'              
  maxMemoryCapacity: 2
  maxVDiskCapacity: 10
  maxCPUCapacity: 2
  maxNASCapacity: 20
  maxArchiveCapacity: 20
  maxNetworkOptTransfer: 5
  maxNetworkPeerTransfer: 15
  maxNumPublicIP: 1

node.ovc__vmislam1:
    os.image: 'ubuntu 16.04 x64'
    disk.size: 10
    datadisks:
        - 'name:disk1 size:50 type:normal'
        - 'name:disk2 size:50 type:normal'
    os.size: 2
    ports:
        - '139:139'
        - '445:445'
        - '137:137'
        - '138:138'
   vdc: 'helloislam'
```
- This blueprint has a miss g8.location parameter cos its dealing with a grid env.
- press on "Execute blueprint"
- Press on "init"
- Press on "install"
- Check the repo instance

**Actual Result**
The confirmation green pop-up message will appear

**Expected Result**
Error message

Hint: If u install the blueprint manully from the cokcpit mahcine by AYS install command, You will get the error.
