### ISSUE TITLE
Internal error when trying to install a g8client

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#203]
Tested on https://artililiumv2.aydo2.com

Blueprint:

```yaml
g8client__client1:
  g8.url: 'gig.demo.greenitglobe.com'
  g8.login: 'artilium_admin'
  g8.password: 'artilium12345'
  g8.account: 'Artilium Account'
```
<img width="592" alt="screen shot 2016-09-20 at 13 19 49" src="https://cloud.githubusercontent.com/assets/13795109/18668317/0f1483a8-7f35-11e6-981e-a64b97784e65.png">
