### ISSUE TITLE
Internal server error when accessing Blueprints

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#204]
Probably related to wrongly formatted blueprint, but nevertheless the Cockpit should be able to react in a less fragile way:

<img width="747" alt="screen shot 2016-09-20 at 15 03 28" src="https://cloud.githubusercontent.com/assets/13795109/18671210/7e5f5f04-7f43-11e6-8ccd-cd86bb68b501.png">

**Comment by yveskerwyn** [comment]
This breaks the complete portal:

<img width="669" alt="screen shot 2016-09-20 at 15 09 20" src="https://cloud.githubusercontent.com/assets/13795109/18671421/4df53c34-7f44-11e6-9cf4-17437810f940.png">

**Comment by yveskerwyn** [comment]
Was related wrongly formatted blueprint:

```yaml
ovc_user__user1:
  g8.client.name: 'client1'
  username:'rthursday'
  email:'reem.khamis@gmail.com'
  provider: 'itsyouonline'
```

Missing space between username: and 'rthursday'
