### ISSUE TITLE
mvp-cockpit: Cannot create data for schema from arguments, value type mismatch

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#298]
http://172.98.207.199:7182/ays81/Repo?repopath=$$ayspath&repo=yves01

blueprint:
```
node.ovc__vm4yves01:
  description: vm for testing autosnapshotting
  bootdisk.size: 10
  memory: 2
  os.image: "Ubuntu 16.04 x64"
  ports: "7122:22"
  vdc: vdc4yves01
```

```
autosnapshotting__snapshotting4yves01:
  vdc: vdc4yves01
  snapshotInterval: '2h'
  cleanupInterval: '1d'
  retention: '5d'

actions:
  - action: install
    actor: autosnapshotting
    service: snapshotting4yves01
```

What is wrong with these blueprints?

The error message is way to verbose, not really helping:

![screen shot 2016-12-05 at 12 03 51](https://cloud.githubusercontent.com/assets/13795109/20882784/f6b93e7c-bae2-11e6-85d0-a6a69c587c21.png)
