### ISSUE TITLE
scality service doesn't have the server data

### ISSUE THREAD

**Issue by ramezsaeed** [Jumpscale/jscockpit#326]
when try to run the s3 scality service to install s3server using this blueprint
```
g8client__main:
    url: 'du-conv-2.demo.greenitglobe.com'
    login: 's3user'
    password: '123456789'
    account: 's3_acc'

vdc__scality22:
    g8client: 'main'
    location: 'du-conv-2'

disk.ovc__disk1:
  size: 1000

s3__s3vm:
    vdc: 'scality22'
    disk:
      - 'disk1'
    hostprefix: 's3app22'
```
## scenario:
1- create new repo from cockpit portal
2- execute the bp from cockpit portal
3- the run status will be OK and all the steps are OK too
4- however if I go to the scality service to get the sercet/access keys, it will be emtpy json
```
root@vm-14:/optvar/cockpit_repos/s3server4/services/vdcfarm!auto_82/vdc!scality24/node!s3vm/os!s3vm/node!app/os!app/scality!app# cat data.json 
{
 "domain":"",
 "keyAccess":"",
 "keySecret":"",
 "os":"app",
 "storageData":"\/data\/data",
 "storageMeta":"\/data\/meta"
```
5- now from the cockpit machine, do ays destroy & ays blueprint & ays install 
now the data.json will be OK and include all the needed info 

```
root@vm-14:/optvar/cockpit_repos/s3server4/services/vdcfarm!auto_82/vdc!scality24/node!s3vm/os!s3vm/node!app/os!app/scality!app# cat data.json 
{
 "domain":"s3app21-3232242740.gigapps.io",
 "keyAccess":"W7X2BxGxWXxO",
 "keySecret":"YBbEjNdeQrqp",
 "os":"app",
 "storageData":"\/data\/data",
 "storageMeta":"\/data\/meta"
```
