### ISSUE TITLE
Deceiving run info after executing the s3 blueprint

### ISSUE THREAD

**Issue by john-kheir** [Jumpscale/jscockpit#329]
Executing and running this blueprint from the cockpit portal results into clean run , however no docker created on the created vm and even docker.io is not installed
```
g8client__main:
    url: 'du-conv-2.demo.greenitglobe.com'
    login: 'john'
    password: '*****'
    account: 'johnacctest'

vdc__main10:
    g8client: 'main'
    location: 'du-conv-2'

disk.ovc__disk1:
   size: 1000

s3__s3vm10:
    vdc: 'main10'
    disk:
      - 'disk1'
    hostprefix: 's3app22'
```
![bugg22](https://cloud.githubusercontent.com/assets/15011431/21589046/41571f70-d0f6-11e6-87d3-42281196a344.png)

![bugg333](https://cloud.githubusercontent.com/assets/15011431/21589089/d4eaa784-d0f6-11e6-98c3-44c3d97bdccb.png)

## Note 
 Executing the same blueprint ,from any other machine that has ays, worked fine
## Software Version
JumpScale

    Core: 8.1.0rc2-4-g776daea
    Portal: 8.1.0rc2-1-gb748c00

JSCockpit

    JSCockpit: 8.1.0rc2
