### ISSUE TITLE
How to install a Cockpit if you don't have the private key of the DNS server 

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#368]
In the blueprint for creating a new Cockpit you have to specify the `{dns.sshkey}` to the private key of the DNS server and the `{domain}` name (FQDN) for the Cockpit:

```
sshkey__dns:
   key.path: '{path}'

cockpit__{cockpit}:
   dns.sshkey: 'dns'
   domain: '{domain}'
```

What if you don't want AYS to create the DNS record, and you want to create it manually instead?

Can you then simply omit the `dns.sshkey: 'dns'` and `domain: '{domain}'`entries?
